### ISSUE TITLE
Unable to install the solution

### ISSUE THREAD

**Issue by pappa75** [lithnet/resourcemanagement-ui-userverification#5]
Hello Ryan,

For some reason the solution cannot be installed on MIM 2016 SP2 (version 4.6.421.0) that is running on SP 2013 (CU April 2021, version 15.0.5337.1000) as the below error appears in the event log after running the command "Install-SPSolution –Identity "user-verification.wsp" –WebApplication "https://mim.somedomain.com" -FullTrustBinDeployment –GACDeployment":

"The Execute method of job definition "SPSolutionDeploymentJobDefinition" (id "67395391-42b9-415d-8399-8d811950410b") threw an exception. Error: Cannot add the specified assembly to the global assembly cache: Microsoft.IdentityManagement.SmsServiceProviderContract.dll." 

This assembly is already installed by MIM.

If also trying to run this cmdlet without  -FullTrustBinDeployment parameter, the following error appears: 

"Install-SPSolution : The solution "user-verification.wsp" is installing
assemblies into the bin directory.  The bin directory is deprecated and
assemblies installed into it are no longer partially trusted, they are granted
full trust.  This solution should be updated to install its assemblies into
the Global Assembly Cache (GAC) instead.  If you fully trust this solution,
and want to continue installing it into the obsolete bin directory, specify
the -FullTrustBinDeployment parameter to suppress this warning.
At line:1 char:1
+ Install-SPSolution -Identity "user-verification.wsp" -WebApplication  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Share...InstallSolu
   tion:SPCmdletInstallSolution) [Install-SPSolution], SPCmdletException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletInstallS
   olution"

**Comment by ryannewington** [comment]
@Manjunath-hk1 is this a known issue? Have we seen this in our environments?

**Comment by Manjunath-hk1** [comment]
@ryannewington  We did not had any installation issue.
@pappa75 I am sharing the below commands and I see that -Force is missing and our webapplication address was without https for installation. I can further dig if you still have issue.
Add-PSSnapin Microsoft.SharePoint.PowerShell
Add-SPSolution -LiteralPath "C:\wsp\user-verification.wsp"
Install-SPSolution -Identity "user-verification.wsp" -WebApplication "http://idm.fim.local" -Force -GACDeployment -FullTrustBinDeployment
Enable-SPFeature -Identity user-verification -Url "http://idm.fim.local/IdentityManagement"

**Comment by pappa75** [comment]
Using the -Force parameter did not help either as the deployment fails with exactly the same error. Our web app is using https only so I am not able to test with http.

**Comment by ryannewington** [comment]
Just doing a quick google and it seems to be a not-unknown problem with SharePoint packages.

One suggestion from here is to use gacutil to install the DLL manually and see if you get a more detailed error message that could help you figure out what is wrong. 

https://sharepoint.stackexchange.com/questions/135865/install-spsolution-cannot-add-the-specified-assembly-to-the-global-assembly-cach

Rename the .wsp to .cab and you can open it in explorer and copy the SMS provider dll out.

**Comment by pappa75** [comment]
Thx Ryan for the tips but since the server where I am trying to deploy the wsp package is a MIM Portal/Service server, it already has the Microsoft.IdentityManagement.SmsServiceProviderContract.dll installed in its assembly.
![image](https://user-images.githubusercontent.com/30044034/116074007-cdecfe00-a699-11eb-80d4-31be7aa28ea6.png)

 In theory it could be reinstalled using the gacutil with a force parameter but this wont help solving this issue. Also this dll cannot be removed using the gacutil since there are dependencies towards MIM.

**Comment by pappa75** [comment]
After forcing the install of the "Microsoft.IdentityManagement.SmsServiceProviderContract.dll" using gacutil (that overwrote the existing one), the deployment to the web app actually succeeded. Tested also sending the SMS which worked great as well.
